"""del unique grz

Revision ID: 0999b1920e9d
Revises: 41fe1b236959
Create Date: 2024-06-03 15:22:07.565445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0999b1920e9d'
down_revision: Union[str, None] = '41fe1b236959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_grz_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_grz_key', 'user', ['grz'])
    # ### end Alembic commands ###
