"""add partnerAndTagsStage

Revision ID: 14f76da7ef83
Revises: 23350da144c9
Create Date: 2024-05-27 22:08:12.211987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f76da7ef83'
down_revision: Union[str, None] = '23350da144c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stagePartner',
    sa.Column('SP_id', sa.Integer(), nullable=False),
    sa.Column('SP_stage', sa.Integer(), nullable=True),
    sa.Column('SP_partner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SP_partner'], ['partner.partner_id'], ),
    sa.ForeignKeyConstraint(['SP_stage'], ['stage.stage_id'], ),
    sa.PrimaryKeyConstraint('SP_id')
    )
    op.create_table('stageTags',
    sa.Column('ST_id', sa.Integer(), nullable=False),
    sa.Column('ST_stage', sa.Integer(), nullable=True),
    sa.Column('ST_tags', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ST_stage'], ['stage.stage_id'], ),
    sa.ForeignKeyConstraint(['ST_tags'], ['tagsStage.tag_id'], ),
    sa.PrimaryKeyConstraint('ST_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stageTags')
    op.drop_table('stagePartner')
    # ### end Alembic commands ###
