"""add users comp

Revision ID: 1fd056ec4d14
Revises: fe1a3bc4cb57
Create Date: 2024-06-03 11:36:14.069442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd056ec4d14'
down_revision: Union[str, None] = 'fe1a3bc4cb57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('front',
    sa.Column('front_id', sa.Integer(), nullable=False),
    sa.Column('front_din_brand', sa.String(length=50), nullable=True),
    sa.Column('front_amp_brand', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('front_id')
    )
    op.create_table('sub',
    sa.Column('sub_id', sa.Integer(), nullable=False),
    sa.Column('sub_din_brand', sa.String(length=50), nullable=True),
    sa.Column('sub_amp_brand', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('sub_id')
    )
    op.create_table('back',
    sa.Column('back_id', sa.Integer(), nullable=False),
    sa.Column('back_din_brand', sa.String(length=50), nullable=True),
    sa.Column('back_amp_brand', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('back_id')
    )
    op.create_table('battery',
    sa.Column('battery_id', sa.Integer(), nullable=False),
    sa.Column('battery_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('battery_id')
    )
    op.add_column('user', sa.Column('front', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('sub', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('back', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('battery', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'sub', ['sub'], ['sub_id'])
    op.create_foreign_key(None, 'user', 'battery', ['battery'], ['battery_id'])
    op.create_foreign_key(None, 'user', 'back', ['back'], ['back_id'])
    op.create_foreign_key(None, 'user', 'front', ['front'], ['front_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'battery')
    op.drop_column('user', 'back')
    op.drop_column('user', 'sub')
    op.drop_column('user', 'front')
    op.drop_table('battery')
    op.drop_table('back')
    op.drop_table('sub')
    op.drop_table('front')
    # ### end Alembic commands ###
