"""add photoAndVideoStage

Revision ID: 23350da144c9
Revises: f238249e689e
Create Date: 2024-05-27 21:59:09.281729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23350da144c9'
down_revision: Union[str, None] = 'f238249e689e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photoStage',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(length=200), nullable=True),
    sa.Column('photo_stage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_stage'], ['stage.stage_id'], ),
    sa.PrimaryKeyConstraint('photo_id'),
    sa.UniqueConstraint('photo_path')
    )
    op.create_table('videoStage',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('video_path', sa.String(length=200), nullable=True),
    sa.Column('video_stage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_stage'], ['stage.stage_id'], ),
    sa.PrimaryKeyConstraint('video_id'),
    sa.UniqueConstraint('video_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videoStage')
    op.drop_table('photoStage')
    # ### end Alembic commands ###
