"""change party

Revision ID: 81dda1ac54cd
Revises: 925c8f872b9a
Create Date: 2024-06-03 20:20:17.389430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81dda1ac54cd'
down_revision: Union[str, None] = '925c8f872b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participant', 'stage', ['stage_id'], ['stage_id'])
    op.drop_constraint('participantClass_PC_stage_fkey', 'participantClass', type_='foreignkey')
    op.drop_column('participantClass', 'PC_stage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participantClass', sa.Column('PC_stage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('participantClass_PC_stage_fkey', 'participantClass', 'stage', ['PC_stage'], ['stage_id'])
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'stage_id')
    # ### end Alembic commands ###
