"""add table for party

Revision ID: 925c8f872b9a
Revises: 0999b1920e9d
Create Date: 2024-06-03 19:58:59.018222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925c8f872b9a'
down_revision: Union[str, None] = '0999b1920e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('number_party', sa.String(length=3), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_table('participantClass',
    sa.Column('PC_id', sa.Integer(), nullable=False),
    sa.Column('PC_participant', sa.Integer(), nullable=True),
    sa.Column('PC_class', sa.Integer(), nullable=True),
    sa.Column('PC_stage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['PC_class'], ['class.id_class'], ),
    sa.ForeignKeyConstraint(['PC_participant'], ['participant.participant_id'], ),
    sa.ForeignKeyConstraint(['PC_stage'], ['stage.stage_id'], ),
    sa.PrimaryKeyConstraint('PC_id')
    )
    op.create_table('result',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('result_value', sa.String(length=3), nullable=True),
    sa.Column('result_PC', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['result_PC'], ['participantClass.PC_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('participantClass')
    op.drop_table('participant')
    # ### end Alembic commands ###
