"""add newsPartnerss

Revision ID: c4034b236e06
Revises: e765fbe279a3
Create Date: 2024-05-27 21:36:29.364828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4034b236e06'
down_revision: Union[str, None] = 'e765fbe279a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsPartner',
    sa.Column('np_id', sa.Integer(), nullable=False),
    sa.Column('np_name', sa.String(length=40), nullable=True),
    sa.Column('np_photo', sa.String(length=500), nullable=True),
    sa.Column('np_partId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['np_partId'], ['partner.partner_id'], ),
    sa.PrimaryKeyConstraint('np_id'),
    sa.UniqueConstraint('np_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsPartner')
    # ### end Alembic commands ###
