"""add users comp1

Revision ID: dba5d7b0e60d
Revises: 1fd056ec4d14
Create Date: 2024-06-03 12:02:40.571548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba5d7b0e60d'
down_revision: Union[str, None] = '1fd056ec4d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('back', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'back', 'user', ['user_id'], ['id'])
    op.add_column('battery', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'battery', 'user', ['user_id'], ['id'])
    op.add_column('front', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'front', 'user', ['user_id'], ['id'])
    op.add_column('sub', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sub', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_sub_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_front_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_back_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_battery_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'front')
    op.drop_column('user', 'back')
    op.drop_column('user', 'sub')
    op.drop_column('user', 'battery')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('battery', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('sub', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('back', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('front', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_battery_fkey', 'user', 'battery', ['battery'], ['battery_id'])
    op.create_foreign_key('user_back_fkey', 'user', 'back', ['back'], ['back_id'])
    op.create_foreign_key('user_front_fkey', 'user', 'front', ['front'], ['front_id'])
    op.create_foreign_key('user_sub_fkey', 'user', 'sub', ['sub'], ['sub_id'])
    op.drop_constraint(None, 'sub', type_='foreignkey')
    op.drop_column('sub', 'user_id')
    op.drop_constraint(None, 'front', type_='foreignkey')
    op.drop_column('front', 'user_id')
    op.drop_constraint(None, 'battery', type_='foreignkey')
    op.drop_column('battery', 'user_id')
    op.drop_constraint(None, 'back', type_='foreignkey')
    op.drop_column('back', 'user_id')
    # ### end Alembic commands ###
