"""add partnerss

Revision ID: e765fbe279a3
Revises: 
Create Date: 2024-05-14 22:45:00.594395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e765fbe279a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id_class', sa.Integer(), nullable=False),
    sa.Column('name_class', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id_class')
    )
    op.create_index(op.f('ix_class_name_class'), 'class', ['name_class'], unique=True)
    op.create_table('partner',
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('partner_name', sa.String(length=40), nullable=True),
    sa.Column('partner_desc', sa.String(length=500), nullable=True),
    sa.Column('partner_logo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('partner_id'),
    sa.UniqueConstraint('partner_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner')
    op.drop_index(op.f('ix_class_name_class'), table_name='class')
    op.drop_table('class')
    # ### end Alembic commands ###
