"""add Stage

Revision ID: f238249e689e
Revises: c77a0eae4778
Create Date: 2024-05-27 21:51:25.066747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f238249e689e'
down_revision: Union[str, None] = 'c77a0eae4778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage',
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=True),
    sa.Column('stage_desc', sa.String(length=1000), nullable=True),
    sa.Column('stage_photo', sa.String(length=200), nullable=True),
    sa.Column('stage_city', sa.String(length=200), nullable=True),
    sa.Column('stage_place', sa.String(length=200), nullable=True),
    sa.Column('stage_date', sa.DateTime(), nullable=True),
    sa.Column('stage_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stage_type'], ['typeStage.type_id'], ),
    sa.PrimaryKeyConstraint('stage_id'),
    sa.UniqueConstraint('stage_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage')
    # ### end Alembic commands ###
